const RESTAURANTS = require('./restaurants');

module.exports = {
  ptiflo: [
    RESTAURANTS.BURGER_KING,
    RESTAURANTS.MC_DONALDS,
    RESTAURANTS.L_ENDROIT,
    RESTAURANTS.SUBWAY,
    RESTAURANTS.HIPPOPOTAMUS,
    RESTAURANTS.AMELIE_CREPE,
  ],
  antoine: [
    RESTAURANTS.PARADIS_DU_FRUIT,
    RESTAURANTS.GOURMIX,
    RESTAURANTS.DOCK40,
    RESTAURANTS.FRATTELI,
    RESTAURANTS.AMELIE_CREPE,
  ],
  marine: [
    RESTAURANTS.AMELIE_CREPE,
    RESTAURANTS.HIPPOPOTAMUS,
    RESTAURANTS.LA_CRIEE,
    RESTAURANTS.WOKO,
  ],
  renaud: [
    RESTAURANTS.BURGER_KING,
    RESTAURANTS.MC_DONALDS,
    RESTAURANTS.AMELIE_CREPE,
  ],
  pierre: [
    RESTAURANTS.WOKO,
    RESTAURANTS.HIPPOPOTAMUS,
    RESTAURANTS.STEAK_N_SHAKE,
    RESTAURANTS.WAFFLE_FACTORY,
    RESTAURANTS.DOCK40,
    RESTAURANTS.AMELIE_CREPE,
  ],
  miflo: [
    RESTAURANTS.MC_DONALDS,
    RESTAURANTS.SELCIUS,
    RESTAURANTS.BURGER_KING,
    RESTAURANTS.AMELIE_CREPE,
  ],
  mehdi: [
    RESTAURANTS.MON_SALADE_BAR,
    RESTAURANTS.PARADIS_DU_FRUIT,
    RESTAURANTS.MC_DONALDS,
    RESTAURANTS.BURGER_KING,
    RESTAURANTS.WAFFLE_FACTORY,
    RESTAURANTS.AMELIE_CREPE,
  ],
  virgile: [
    RESTAURANTS.WOKO,
    RESTAURANTS.WAFFLE_FACTORY,
    RESTAURANTS.GOURMIX,
    RESTAURANTS.PIADA,
    RESTAURANTS.CAFE_HANOI,
    RESTAURANTS.BAILI,
    RESTAURANTS.SUSHI_SHOP,
    RESTAURANTS.GOURMIX,
    RESTAURANTS.PIADA,
    RESTAURANTS.AMELIE_CREPE,
  ]
};
