const RESTAURANTS = require('./restaurants');

module.exports = {
  ptiflo: [
    RESTAURANTS.BURGER_KING,
    RESTAURANTS.MC_DONALDS,
    RESTAURANTS.L_ENDROIT,
    RESTAURANTS.SUBWAY,
    RESTAURANTS.HIPPOPOTAMUS
  ],
  antoine: [
    RESTAURANTS.PARADIS_DU_FRUIT,
    RESTAURANTS.GOURMIX,
    RESTAURANTS.DOCK40,
    RESTAURANTS.FRATTELI
  ],
  marine: [],
  renaud: [RESTAURANTS.BURGER_KING, RESTAURANTS.MC_DONALDS],
  pierre: [
    RESTAURANTS.WOKO,
    RESTAURANTS.HIPPOPOTAMUS,
    RESTAURANTS.STEAK_N_SHAKE,
    RESTAURANTS.WAFFLE_FACTORY,
    RESTAURANTS.DOCK40
  ],
  miflo: [RESTAURANTS.MC_DONALDS, RESTAURANTS.SELCIUS, RESTAURANTS.BURGER_KING],
  mehdi: [
    RESTAURANTS.MON_SALADE_BAR,
    RESTAURANTS.PARADIS_DU_FRUIT,
    RESTAURANTS.MC_DONALDS,
    RESTAURANTS.BURGER_KING
  ],
  virgile: [
  RESTAURANTS.WOKO,
  RESTAURANTS.WAFFLE_FACTORY,
  RESTAURANTS.GOURMIX,
  RESTAURANTS.PIADA,
  RESTAURANTS.CAFE_HANOI,
  RESTAURANTS.BAILI,
  RESTAURANTS.SUSHI_SHOP,
  RESTAURANTS.GOURMIX,
  RESTAURANTS.PIADA,
  ]
};
