module.exports = {
  BURGER_KING: 'Burger King',
  MC_DONALDS: 'McDonalds',
  SUBWAY: 'Subway',
  L_ENDROIT: "l'Endroit",
  HIPPOPOTAMUS: 'Hippopotamus',
  WOKO: 'Woko',
  DOCK40: 'Dock40',
  STEAK_N_SHAKE: "Steak'n'Shake",
  WAFFLE_FACTORY: 'Waffle Factory',
  PARADIS_DU_FRUIT: 'Paradis du fruit',
  GOURMIX: 'Gourmix',
  FRATTELI: 'Fratteli',
  MON_SALADE_BAR: 'Mon Salade Bar',
  SELCIUS: 'Selcius',
  PIADA: 'Piada',
  RAZOWSKI: 'Razowski',
  GOMEX: 'Gomex',
  CAFE_HANOI: 'Café Hanoï',
  OUEST_EXPRESS: 'Ouest Express',
  INTERMEZZO: 'Intermezzo',
  L_ATELIER_DU_PIZZAI: "L'atelier du Pizzailo",
  BAILI: 'Baili',
  SUSHI_SHOP: 'Sushi Shop',
  BOULANGERIE_DU_BOUT_DU_MONDE: 'La boulangerie du bout du monde',
  MOB_HOTEL: 'Mob Hôtel',
  MOULIN_A_SALADES: 'Le moulin à salades'
};
